
# set the input path and the Output path
input: ./Input/
output: ./Inter_output/df_B_drop.csv

# the discard option
months: [1,2,6,7,8,9,10,11,12]
#discard:
#  start_month: 3
#  end_month: 11
# set the engineer option
TimeFE: True
WeatherFE: True
StatFE: True
ShiftFE: True
DiffFE: True