
# set the input path and the Output path
input: ./Input/
output: ./Inter_output/df_f3.csv

# the discard option
discard:
  start_month: 3
  end_month: 11
# set the engineer option
TimeFE: True
WeatherFE: True
StatFE: True
ShiftFE: True
DiffFE: True
YearShiftFE: True