
input: ./Inter_output/df_f1.csv

# 命名格式 submission_{feature name}_{model name}_{operation}.csv
output: ./Output/submission_df_f1_lgbm_cv_plus.csv

extra_data: True
extra_data_path: ./Input/Extra_weather_data.csv
# the split option: normal, half_day, user
split: user
cv_plus: True
# set the model option
model:
  name: lgbm
  config:
    num_boost_round: 20000
    params:
      objective: regression
      metric: rmse
      boosting_type: dart #  gbdt
      max_depth: -1
      verbose: -1
      min_data_in_leaf: 50
      learning_rate: 0.07 # 0.03
      subsample: 0.8
      subsample_freq: 1
      feature_fraction: 0.8
      lambda_l1: 1
      lambda_l2: 2
      zero_as_missing: True
      first_metric_only: True


